export const CHANGE_SINGER_LIST = 'singer/CHANGE_SINGER_LIST';
export const CHANGE_PAGE_COUNT = 'singer/CHANGE_PAGE_COUNT';
export const CHANGE_ENTER_LOADING = 'singer/CHANGE_ENTER_LOADING';
export const CHANGE_PULLUP_LOADING = 'singer/CHANGE_PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'singer/CHANGE_PULLDOWN_LOADING';
